# Generated by Django 4.1.6 on 2023-03-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outgoing_Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Connection_Name", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=300)),
                ("Username", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name="Node",
            new_name="Incoming_Node",
        ),
    ]
