# Generated by Django 4.1.6 on 2023-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_groups_alter_author_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
