# Generated by Django 4.1.6 on 2023-02-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.CharField(default='http://localhost/8000/', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
