# Generated by Django 4.1.6 on 2023-02-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_author_host_alter_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(default='http://localhost/8000/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://localhost/8000/'),
        ),
    ]
