# Generated by Django 4.1.6 on 2023-02-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_alter_author_email'),
        ('author', '0009_author_url_alter_author_host'),
    ]

    operations = [
    ]
