# Generated by Django 4.1.6 on 2023-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_merge_20230228_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://localhost:8000/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http://localhost:8000/'),
        ),
    ]
