# Generated by Django 4.1.6 on 2023-03-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0013_alter_author_host_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
