# Generated by Django 4.1.6 on 2023-03-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0018_alter_author_host_alter_author_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="remote_id",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
