# Generated by Django 4.1.6 on 2023-03-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0019_author_remote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="remote_name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
