version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
