# Generated by Django 4.1.6 on 2023-03-24 19:09


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_body_alter_post_image_file_and_more'),

    ]

    operations = [
        migrations.AlterField(

            model_name="post",
            name="dateEdited",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
