# Generated by Django 4.1.6 on 2023-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_dateedited"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="remote_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
