# Generated by Django 4.1.6 on 2023-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_remote_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
