# Generated by Django 4.1.6 on 2023-02-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
