# Generated by Django 4.1.6 on 2023-02-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_author_post_author_id_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=200),
        ),
    ]
