# Generated by Django 4.1.6 on 2023-03-03 01:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(blank=True, default='text/plain', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
