name: Django CI

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: rtCamp/action-cleanup@master
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: backend/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: backend/
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          python manage.py test

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: rtCamp/action-cleanup@master
      - uses: actions/checkout@master

      - name: Copy repo to VM
        uses: appleboy/scp-action@master
        env:
          HOST: ${{secrets.HOST}}
          USERNAME: ${{secrets.USERNAME}}
          PORT: ${{secrets.PORT}}
          KEY: ${{secrets.KEY}}
        with:
          source: "./"
          target: "~/prod"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{secrets.HOST}}
          USERNAME: ${{secrets.USERNAME}}
          PORT: ${{secrets.PORT}}
          KEY: ${{secrets.KEY}}
          script: |
            cd ~/prod
            docker system prune -f && docker-compose down && docker-compose up --build -d
